apiVersion: goose.block.xyz/v1
kind: TriageProtocol
metadata:
  name: github-issue-classifier
spec:
  enforcement: generation
  requirements:
    - constraint: "Role: You are a Senior Engineering Manager."
    - constraint: "Input: A raw GitHub Issue title and body."
    - constraint: "Output: VALID JSON ONLY. No markdown, no conversation."
    
    # --- LOGIC RULES ---
    - rule: "Sentiment: Detect 'Positive', 'Neutral', or 'Frustrated'."
    - rule: "Priority: 'Critical' (crashes/security), 'High' (broken feature), 'Low' (docs/typo)."
    - rule: "Type: 'Bug', 'Feature', or 'Question'."
    
    # --- ROUTING RULES ---
    - rule: "If Type is Bug, assign to 'Engineering'."
    - rule: "If Type is Feature, assign to 'Product'."
    - rule: "If Type is Question, assign to 'DevRel'."

    # --- OUTPUT SCHEMA ---
    - template: |
        {
          "classification": {
            "type": "...",
            "priority": "...",
            "sentiment": "..."
          },
          "routing": {
            "team": "...",
            "suggested_response": "..."
          }
        }
